/**
 * End-to-end audit through a real browser.
 *
 * Drives Chromium with a synthesised caller as the microphone, so the whole
 * path runs: mic → VAD worklet → WebSocket → STT → agent → TTS → playback.
 * Server-side tests inject VAD events directly and cannot catch bugs in any of
 * the first three hops — every serious defect found so far lived there.
 *
 *   node scripts/browser-audit.mjs            # regenerates the fixture
 *   node scripts/browser-audit.mjs --keep     # reuse an existing fixture
 */
import { chromium } from 'playwright'
import { execSync } from 'node:child_process'
import { existsSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import 'dotenv/config'

const DIR = join(tmpdir(), 'vaani-audit')
const WAV = join(DIR, 'caller.wav')
const LINE = 'Hello, I would like to book a teeth cleaning appointment please.'

// The fixture is regenerated by default: a missing WAV makes Chromium deliver
// pure silence with no error at all, which reads exactly like a broken agent.
if (!existsSync(WAV) || !process.argv.includes('--keep')) {
  mkdirSync(DIR, { recursive: true })
  const key = process.env.ELEVENLABS_API_KEY
  if (!key) throw new Error('ELEVENLABS_API_KEY required to synthesise the caller')
  const res = await fetch(
    'https://api.elevenlabs.io/v1/text-to-speech/bIHbv24MWmeRgasZH58o?output_format=pcm_16000',
    { method: 'POST', headers: { 'xi-api-key': key, 'content-type': 'application/json' },
      body: JSON.stringify({ text: LINE, model_id: 'eleven_turbo_v2_5' }) })
  if (!res.ok) throw new Error(`synthesis failed: ${res.status}`)
  const { writeFileSync } = await import('node:fs')
  writeFileSync(join(DIR, 'raw.pcm'), Buffer.from(await res.arrayBuffer()))
  // Lead-in silence lets the greeting finish before the caller speaks.
  execSync(`ffmpeg -loglevel error -y -f s16le -ar 16000 -ac 1 -i ${join(DIR,'raw.pcm')} ` +
           `-af "adelay=4000|4000,apad=pad_dur=5" -acodec pcm_s16le -ar 48000 -ac 1 ${WAV}`)
}

const browser = await chromium.launch({ args: [
  '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream',
  `--use-file-for-fake-audio-capture=${WAV}`, '--autoplay-policy=no-user-gesture-required' ] })
const ctx = await browser.newContext({ permissions: ['microphone'], viewport: { width: 1440, height: 900 } })
const page = await ctx.newPage()

const errors = []; const recv = []
page.on('pageerror', (e) => errors.push(String(e)))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
page.on('websocket', (ws) => ws.on('framereceived', (f) => {
  if (typeof f.payload === 'string') { try { recv.push(JSON.parse(f.payload)) } catch {} } }))

await page.goto('http://localhost:3000/console', { waitUntil: 'networkidle' })
await page.getByRole('button', { name: /take a call/i }).click()
await page.waitForTimeout(26000)

const finals = recv.filter((e) => e.type === 'stt.final').map((e) => e.text)
const partials = recv.filter((e) => e.type === 'tts.begin').map((e) => e.text)
const metrics = recv.filter((e) => e.type === 'metrics.turn')

// Live streams each utterance as a growing prefix, so `partials` is mostly the
// same sentence over and over. Collapse to finished utterances: a partial that
// the next one extends is superseded, and only the last of each run survives.
const spoken = partials.filter((t, i) => !(partials[i + 1] ?? '').startsWith(t))

console.log('\n── caller');     finals.forEach((t) => console.log(`   "${t}"`))
console.log('── front desk'); spoken.forEach((t) => console.log(`   "${t}"`))
console.log('── latency'); metrics.forEach((m) => console.log(`   e2e ${Math.round(m.e2eMs)}ms`))

const checks = [
  ['caller was heard',        finals.length > 0],
  // The desk has no personal name and must never invent one to fill the
  // opening pause — the greeting names the practice and nothing else.
  ['greeting names no person §2.1',
    /smile dental/i.test(spoken[0] ?? '') && !/\b(priya|main |i am |this is [A-Z])/i.test(spoken[0] ?? '')],
  ['no tool markup §20',      !spoken.some((t) => /<function|\{/.test(t))],
  ['no stage directions §20', !spoken.some((t) => /[()[\]]/.test(t))],
  // Asking the same thing twice is the tell that context was lost. Compared on
  // finished utterances — comparing stream partials flagged any two turns that
  // happened to open with the same word.
  ['no repeated question §28', spoken.length === new Set(spoken).size],
  ['no console errors',        errors.length === 0],
]
console.log('\n── checks')
let failed = 0
for (const [name, ok] of checks) {
  if (!ok) failed++
  console.log(`  ${ok ? '✓' : '✗'} ${name}`)
}
if (errors.length) console.log('  errors:', errors.slice(0, 3).join(' | '))
await browser.close()
process.exit(failed === 0 ? 0 : 1)
